### ISSUE TITLE
Investigate possible configuration merge problem

### ISSUE THREAD

**Issue by hughbris** [hughbris/grav-plugin-pushy#31]
The last site I set up, I thought I would try to keep the webhook secret for the production environment out of the repo. So I put common settings in `config/plugins/pushy.yaml` including:

```yaml
webhooks:
  path: /_webhooks
  endpoints:
    publish:
      run: fetch-merge-edits
      conditions:
        # branch:
        # committer:
```
then in `env/prod.example.com/config/plugins/pushy.yaml` I put:

```yaml
webhooks:
  enabled: true
  secret: MY_SECRET_HERE_NOT_IN_GIT
```
I expected the configs to merge, but I got an error instead saying the `path` property of `$webhook` was not defined at [line 172 of pushy.php](https://github.com/hughbris/grav-plugin-pushy/blob/87ff8375dd24d7ef6acbbc003b3c98a53c3e7f18/pushy.php#L172).

I don't currently have time to reproduce and investigate this, but it seems worth trying to in future.

**Comment by pamtbaau** [comment]
Using three config files:
1. *user/plugins/myplugin/myplugin.yaml*, 
2. *user/config/plugins/myplugin.yaml*, 
3. *user/env/mydomain/config/plugins/myplugin.yaml*), 

It seems that:
- Unique toplevel variables are added to the final config.
- Non unique toplevel variables are replaced/overridden, where config 2 overrides 1 and 3 overrides 1/2
- There is no recursion taking place in nested variables

**Comment by hughbris** [comment]
Thanks for looking into this!

It's hard for me to recall, but I think I have _once_ experienced this in Admin or an admin plugin. I think it's called a deep merge and usually I assume it happens. This is my normal system debug setup:

`config/system.yaml`:
```
debugger:
  enabled: false
  provider: debugbar
  censored: true
```
then in `env/.../config/system.yaml`:
```
debugger:
  enabled: true # dev, staging
  censored: false # (local) dev
```
`provider` works here, but as you say, perhaps that is because it is scalar. That also may explain why I recall experiencing this at least once.

[`\Grav\Common\Plugin->mergeConfig()`](https://learn.getgrav.org/17/api#class-grav-common-plugin) has `deep` as a parameter, defaulting to `false`. I guess I will look into where/how that is typically invoked.

I am having trouble imagining why a deep merge would _not_ be desirable.

**Comment by pamtbaau** [comment]
Did some more tracing on how config files are being "merged".

This is the code where the configs are being merged: https://github.com/rockettheme/toolbox/blob/74b3c55d6883cf5fed7432e85e2a81a9f61ed4cd/Blueprints/src/BlueprintSchema.php#L436-L461

Considering the name of the class (`BlueprintsSchema`) and its 3rd parameter `$rules` it thought it might take the blueprint for the plugin into account.

So I:
- Added the following to the form definition inside */user/plugins/myplugin/blueprints.yaml*:
  ```
  shared:
    type: text
  nestedMap.shared:
    type: text
  nestedMap.fromUserPluginsFixFileFieldFolder:
    type: text
  nestedMap.fromUserConfigPluginsFolder:
    type: text
  nestedMap.fromUserEnvDomainConfigPluginsFixFileFieldFolder:
    type: text
  ```
- Created */user/plugins/myplugin/myplugin.yaml*:
```
shared: fromUserPluginsFixFileFieldFolder
fromUserPluginsFixFileFieldFolder: true
nestedMap:
  shared: fromUserPluginsFixFileFieldFolder
  fromUserPluginsFixFileFieldFolder: fromUserPluginsFixFileFieldFolder
```
- Created */user/config/plugins/myplugin.yaml*:
```
shared: fromUserConfigPluginsFolder
fromUserConfigPluginsFolder: true
nestedMap:
  shared: fromUserConfigPluginsFolder
  fromUserConfigPluginsFolder: fromUserConfigPluginsFolder
nestedArray:
  - shared: fromUserConfigPluginsFolder
  - fromUserConfigPluginsFolder: fromUserConfigPluginsFolder
```
- Created */user/env/domain/config/plugins/myplugin.yaml*:
```
shared: fromUserEnvDomainConfigPluginsFolder
fromUserEnvDomainConfigPluginsFolder: true
nestedMap:
  shared: fromUserEnvDomainConfigPluginsFolder
  fromUserEnvDomainConfigPluginsFolder: fromUserEnvDomainConfigPluginsFolder
```

The above yields the following final config:
  ```
  shared: fromUserEnvDomainConfigPluginsFolder

  fromUserPluginsMyPluginFolder: true
  fromUserConfigPluginsFolder: true
  fromUserDevDomainConfigPluginsFolder: true

  nestedMap:
    shared: fromUserDevDomainConfigPluginsFolder
    fromUserPluginsMyPluginFolder: fromUserPluginsMyPluginFolder
    fromUserConfigPluginsFolder: fromUserConfigPluginsFolder
    fromUserDevDomainConfigPluginsFolder: fromUserDevDomainConfigPluginsFolder
  ```

Cautious conclusions:
- Fields that are shared between configs are being overridden by superseding configs
- Fields that are unique to each config are added to the next superseding config
- Nested Map:
  - Shared fields are overridden
  - Unique fields in shared Map are carried over to superseding configs.

Unfortunately, I haven't found a solution for nested Arrays (yet).

**Comment by hughbris** [comment]
Thanks again for the testing I find so tedious to perform myself!

> Unfortunately, I haven't found a solution for nested Arrays (yet).

I wonder if that is by design or a bug. In any case, I couldn't imagine a scenario where I don't want a deep merge. Having said that, I've just discovered an exception and it would surprise me if the behaviour is deliberate. In a new plugin I have this blueprint:

```yaml
    assets:
      type: section
      title: Assets
      fields:

        .js:
          type: url
          label: Javascript URL
          toggleable: true

        .css:
          type: url
          label: CSS URL
          toggleable: true
```
and defaults set in the plugin:

```yaml
assets:
  js: 'https://cdn.example.org/default.min.js'
  css: 'https://cdn.example.org/default.min.css'
```
My plan was to provide a toggle so that a local copy of those assets could be stored in the plugin and used when these properties are not set. I think that could have been a nice intuitive UI. I prefer the CDN resources to be used by default.

What happened when I toggled one of these `off` in Admin is that the property was removed in the local YAML (as desired), but Admin shows it toggled _on_ after save. That makes sense too when we think of the configs merging, but it makes such toggles useless when there is a default set! Would be good if Grav could implement an exception for toggleable fields, but I haven't yet considered all the side effects that might have.

I can think of a few simple alternatives to work around this, but I was hoping this elegant pattern might work for me. It might be worthwhile surveying similar plugins that allow loaded assets to be configured. When I have pushed this code, I will create an issue and link it here.
